### PR TITLE
Revert available versions summary

### PR DESCRIPTION
**Pull request by aganders3**
As noted in https://github.com/napari/npe2api/pull/9#issuecomment-1325633613, PR #9 broke the plugin manager on existing versions of napari due to a bug in `npe2` that makes it choke on extra fields. This reverts that change and adds a test that mirrors the code in napari.

I'd like to put that back in eventually but will make a PR to fix the issue in `npe2` first. For now the change should be reverted to fix existing napari installations.

Also note in that thread Talley requested review from a different core dev so any help here is appreciated!

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]

**Comment by goanpeca** [comment]
Merging as this seems critical!

**Comment by potating-potato** [comment]
going to merge this one since the conversation in #9 confirms the findings

**Comment by jni** [comment]
Does anyone know how the Vercel auth works?

**Comment by tlambert03** [comment]
you don't need to worry about it, it will deploy

**Comment by jni** [comment]
Comfortable is a strong word @tlambert03 😅

**Comment by jni** [comment]
Looks pretty sweet though, I think I should spend more time looking at Vercel. 😊

**Comment by aganders3** [comment]
Thanks for merging!

> Looks pretty sweet though, I think I should spend more time looking at Vercel. 😊 

+1

The per-branch previews seem really neat - might have prevented this if I had tested with the preview first 😬.

**Pull request merged**
