### PR TITLE
Update permissions in fetch workflow

### LINKED ISSUE #20: Fetch manifests is failing
It looks like it's been failing for a couple weeks.

I think it's consistently failing when trying to commit the changes back to the repo - 403 error so maybe just an expired token or something?
```
remote: Permission to napari/npe2api.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/napari/npe2api/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

### PR DESCRIPTION
**Pull request by aganders3**
Testing to see if this would fix #20

### CODE REVIEW

**Comment by aganders3** [comment]
This change allowed the workflow to successfully complete with a workflow-dispatch run:
https://github.com/napari/npe2api/actions/runs/6552537248

Running this check as triggered by the PR is not sufficient as the commit step is skipped for PRs.

**Comment by Czaki** [comment]
could you remove github bot commit for simplify review?

**Comment by aganders3** [comment]
The bot commit is removed now. I'm not 100% sure this will fix the issue, but seems promising.

This is the config suggested in the README for the auto-commit action: https://github.com/stefanzweifel/git-auto-commit-action#usage

Also it's already configured this way in the bigquery workflow that is still passing:
https://github.com/napari/npe2api/blob/65e3f5773671bd4d27338ab1adc35edfc56020bb/.github/workflows/bigquery.yml#L14

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
Lets merge and observe in the wild.

**Pull request merged**
